# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler
name: Auto reviews release
on: pull_request
jobs:
  reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Auto reviews branches
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          EVENT_TYPE: APPROVE
          BRANCHES: +
          AUTHOR: +
          MESSAGE: Nice approve from github bot.
